_BASE_: "mmcr_base.yaml"

TRAINER:
  LR: 5e-5
  BATCH_SIZE: 8

DATALOADER:
  TRAIN_PERCENTAGE: 100
  FINETUNE_STOCKHOLM: True
  STOCKHOLM_BUILDINGS:
    INCLUDE: True
    YEAR: 2018
  STOCKHOLM_YEARS: [2018, 2023]

CONSISTENCY_TRAINER:
  LOSS_FACTOR: 0.01