_BASE_: "base.yaml"

MODEL:
  TYPE: 'dtlatefusionsiameseunet'

DATALOADER:
  INPUT_MODE: 's1s2'
  INCLUDE_BUILDING_LABELS: True
  INCLUDE_UNLABELED: True
  USE_TRAIN_AS_UNLABELED: True
  TRAIN_PERCENTAGE: 100

CONSISTENCY_TRAINER:
  LOSS_TYPE: 'PowerJaccardLoss'