_BASE_: "base.yaml"

MODEL:
  TYPE: 'dtsiameseunet'
  IN_CHANNELS: 4

DATALOADER:
  INPUT_MODE: 's2'
  INCLUDE_BUILDING_LABELS: True
  INCLUDE_UNLABELED: True
  USE_TRAIN_AS_UNLABELED: True

CONSISTENCY_TRAINER:
  LOSS_TYPE: 'PowerJaccardLoss'